name: tostore
description: Fast distributed AI vector database and persistent local storage engine. High-performance key-value store supporting SQL, NoSQL, offline cache and encrypted data.
version: 3.1.2
homepage: https://github.com/tocreator/tostore
repository: https://github.com/tocreator/tostore
documentation: https://github.com/tocreator/tostore/wiki

topics:
  - database
  - storage
  - vector-database
  - sql
  - key-value

environment:
  sdk: ^3.5.4

dependencies:
  path: ^1.9.1
  archive: ^4.0.7
  web: ^1.1.1
  ffi: ^2.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.28.0
