import 'dart:convert';

import 'background_write_mode.dart';
import 'meta_info.dart';
import 'table_schema.dart';
import 'wal_pointer.dart';

/// migration task, for storing table structure, table data migration operations
class MigrationTask {
  // task id
  final String taskId;
  // table name
  final String tableName;
  // whether the table structure is updated
  final bool isSchemaUpdated;
  // pending migration spaces
  final List<String> pendingMigrationSpaces;
  // migration operations
  final List<MigrationOperation> operations;
  // create time
  final DateTime createTime;
  // directory index
  final int dirIndex;
  // whether the migration task is auto generated
  final bool isAutoGenerated;
  // snapshot of the source schema before any schema operation is applied
  final TableSchema? oldSchemaSnapshot;
  // snapshot of the logical target schema after schema cutover
  final TableSchema? targetSchemaSnapshot;
  // snapshot of source field storage layout before any schema operation
  final FieldStorageLayout? oldFieldLayoutSnapshot;
  // table name after schema operations are applied (rename-aware)
  final String? currentTableName;
  // WAL boundary pointer captured at schema cutover time
  final WalPointer? schemaCutoverWalPointer;
  // force physical data rewrite even if operations are logically metadata-only
  final bool forceDataMigration;
  // per-space PK checkpoint (base64 encoded MemComparable key bytes)
  final Map<String, String> spaceCheckpointKeys;
  // path to the pre-migration backup
  final String? backupPath;
  // target write mode for background execution
  final BackgroundWriteMode? writeMode;
  // specific index names to build during execution (null means all)
  final List<String>? specificIndexes;

  const MigrationTask({
    required this.taskId,
    required this.tableName,
    required this.isSchemaUpdated,
    required this.pendingMigrationSpaces,
    required this.operations,
    required this.createTime,
    required this.dirIndex,
    this.isAutoGenerated = false,
    this.oldSchemaSnapshot,
    this.targetSchemaSnapshot,
    this.oldFieldLayoutSnapshot,
    this.currentTableName,
    this.schemaCutoverWalPointer,
    this.forceDataMigration = false,
    this.spaceCheckpointKeys = const <String, String>{},
    this.backupPath,
    this.writeMode,
    this.specificIndexes,
  });

  /// create from json
  factory MigrationTask.fromJson(Map<String, dynamic> json) => MigrationTask(
        taskId: json['taskId'] as String,
        tableName: json['tableName'] as String,
        isSchemaUpdated: json['isSchemaUpdated'] as bool,
        pendingMigrationSpaces:
            (json['pendingMigrationSpaces'] as List).cast<String>(),
        operations: (json['operations'] as List)
            .map((e) => MigrationOperation.fromJson(e as Map<String, dynamic>))
            .toList(),
        createTime: DateTime.parse(json['createTime'] as String),
        dirIndex: json['dirIndex'] as int,
        isAutoGenerated: json['isAutoGenerated'] as bool? ?? true,
        oldSchemaSnapshot: json['oldSchemaSnapshot'] != null
            ? TableSchema.fromJson(
                Map<String, dynamic>.from(json['oldSchemaSnapshot'] as Map),
              )
            : null,
        targetSchemaSnapshot: json['targetSchemaSnapshot'] != null
            ? TableSchema.fromJson(
                Map<String, dynamic>.from(json['targetSchemaSnapshot'] as Map),
              )
            : null,
        oldFieldLayoutSnapshot: json['oldFieldLayoutSnapshot'] != null
            ? FieldStorageLayout.fromJson(
                Map<String, dynamic>.from(
                    json['oldFieldLayoutSnapshot'] as Map),
              )
            : null,
        currentTableName: json['currentTableName'] as String?,
        schemaCutoverWalPointer: json['schemaCutoverWalPointer'] != null
            ? WalPointer.fromJson(
                Map<String, dynamic>.from(
                    json['schemaCutoverWalPointer'] as Map),
              )
            : null,
        forceDataMigration: json['forceDataMigration'] as bool? ?? false,
        spaceCheckpointKeys: json['spaceCheckpointKeys'] is Map
            ? Map<String, String>.from(
                json['spaceCheckpointKeys'] as Map,
              )
            : const <String, String>{},
        backupPath: json['backupPath'] as String?,
        writeMode: json['writeMode'] != null
            ? BackgroundWriteMode.values
                .firstWhere((e) => e.name == json['writeMode'])
            : null,
        specificIndexes: (json['specificIndexes'] as List?)?.cast<String>(),
      );

  /// convert to json
  Map<String, dynamic> toJson() => {
        'taskId': taskId,
        'tableName': tableName,
        'isSchemaUpdated': isSchemaUpdated,
        'pendingMigrationSpaces': pendingMigrationSpaces,
        'operations': operations.map((op) => op.toJson()).toList(),
        'createTime': createTime.toIso8601String(),
        'dirIndex': dirIndex,
        'isAutoGenerated': isAutoGenerated,
        'oldSchemaSnapshot': oldSchemaSnapshot?.toJson(),
        'targetSchemaSnapshot': targetSchemaSnapshot?.toJson(),
        'oldFieldLayoutSnapshot': oldFieldLayoutSnapshot?.toJson(),
        'currentTableName': currentTableName,
        'schemaCutoverWalPointer': schemaCutoverWalPointer?.toJson(),
        if (forceDataMigration) 'forceDataMigration': true,
        if (spaceCheckpointKeys.isNotEmpty)
          'spaceCheckpointKeys': spaceCheckpointKeys,
        if (backupPath != null) 'backupPath': backupPath,
        if (writeMode != null) 'writeMode': writeMode!.name,
        if (specificIndexes != null) 'specificIndexes': specificIndexes,
      };

  String? checkpointKeyForSpace(String spaceName) =>
      spaceCheckpointKeys[spaceName];

  MigrationTask upsertCheckpointKeyForSpace(
    String spaceName,
    List<int> keyBytes,
  ) {
    final encoded = base64Encode(keyBytes);
    final updated = Map<String, String>.from(spaceCheckpointKeys);
    updated[spaceName] = encoded;
    return copyWith(spaceCheckpointKeys: updated);
  }

  MigrationTask clearCheckpointKeyForSpace(String spaceName) {
    if (!spaceCheckpointKeys.containsKey(spaceName)) {
      return this;
    }
    final updated = Map<String, String>.from(spaceCheckpointKeys);
    updated.remove(spaceName);
    return copyWith(spaceCheckpointKeys: updated);
  }

  /// set the table structure change status
  MigrationTask setSchemaUpdated(bool updated) => copyWith(
        isSchemaUpdated: updated,
      );

  /// update the pending migration spaces
  MigrationTask updatePendingSpaces(List<String> spaces) => copyWith(
        pendingMigrationSpaces: spaces,
      );

  /// add a single pending migration space
  MigrationTask addPendingSpace(String space) {
    if (pendingMigrationSpaces.contains(space)) {
      return this;
    }
    return copyWith(
      pendingMigrationSpaces: [...pendingMigrationSpaces, space],
    );
  }

  /// remove a single pending migration space
  MigrationTask removePendingSpace(String space) {
    if (!pendingMigrationSpaces.contains(space)) {
      return this;
    }
    return copyWith(
      pendingMigrationSpaces: [
        for (final s in pendingMigrationSpaces)
          if (s != space) s
      ],
    );
  }

  /// create a copy (basic method)
  MigrationTask copyWith({
    String? taskId,
    String? tableName,
    bool? isSchemaUpdated,
    List<String>? pendingMigrationSpaces,
    List<MigrationOperation>? operations,
    DateTime? createTime,
    int? dirIndex,
    bool? isAutoGenerated,
    TableSchema? oldSchemaSnapshot,
    TableSchema? targetSchemaSnapshot,
    FieldStorageLayout? oldFieldLayoutSnapshot,
    String? currentTableName,
    WalPointer? schemaCutoverWalPointer,
    bool? forceDataMigration,
    Map<String, String>? spaceCheckpointKeys,
    String? backupPath,
    BackgroundWriteMode? writeMode,
    List<String>? specificIndexes,
  }) =>
      MigrationTask(
        taskId: taskId ?? this.taskId,
        tableName: tableName ?? this.tableName,
        isSchemaUpdated: isSchemaUpdated ?? this.isSchemaUpdated,
        pendingMigrationSpaces:
            pendingMigrationSpaces ?? this.pendingMigrationSpaces,
        operations: operations ?? this.operations,
        createTime: createTime ?? this.createTime,
        dirIndex: dirIndex ?? this.dirIndex,
        isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
        oldSchemaSnapshot: oldSchemaSnapshot ?? this.oldSchemaSnapshot,
        targetSchemaSnapshot: targetSchemaSnapshot ?? this.targetSchemaSnapshot,
        oldFieldLayoutSnapshot:
            oldFieldLayoutSnapshot ?? this.oldFieldLayoutSnapshot,
        currentTableName: currentTableName ?? this.currentTableName,
        schemaCutoverWalPointer:
            schemaCutoverWalPointer ?? this.schemaCutoverWalPointer,
        forceDataMigration: forceDataMigration ?? this.forceDataMigration,
        spaceCheckpointKeys: spaceCheckpointKeys ?? this.spaceCheckpointKeys,
        backupPath: backupPath ?? this.backupPath,
        writeMode: writeMode ?? this.writeMode,
        specificIndexes: specificIndexes ?? this.specificIndexes,
      );
}

/// Migration operation type
enum MigrationType {
  addField,
  removeField,
  renameField,
  modifyField,
  addIndex,
  removeIndex,
  modifyIndex,
  renameIndex,
  renameTable,
  setPrimaryKeyConfig,
  setTableTtlConfig,
  dropTable,
  addForeignKey,
  removeForeignKey,
  modifyForeignKey,
}

/// model for field update, allow explicit distinction of whether a value is set
class FieldSchemaUpdate {
  final String name;
  final DataType? type;
  final bool? nullable;
  final dynamic defaultValue;
  final bool? unique;
  final String? comment;
  final int? minLength;
  final int? maxLength;
  final num? minValue;
  final num? maxValue;
  final DefaultValueType? defaultValueType;
  final String? fieldId;
  final VectorFieldConfig? vectorConfig;

  // track which properties are explicitly set
  final Map<String, bool> _explicitlySet;

  FieldSchemaUpdate({
    required this.name,
    this.type,
    this.nullable,
    this.defaultValue,
    this.unique,
    this.comment,
    this.minLength,
    this.maxLength,
    this.minValue,
    this.maxValue,
    this.defaultValueType,
    this.fieldId,
    this.vectorConfig,
  }) : _explicitlySet = {
          'type': type != null,
          'nullable': nullable != null,
          'defaultValue':
              true, // defaultValue always considered explicitly set, even if null
          'unique': unique != null,
          'comment':
              true, // comment always considered explicitly set, even if null
          'minLength':
              true, // minLength always considered explicitly set, even if null
          'maxLength':
              true, // maxLength always considered explicitly set, even if null
          'minValue':
              true, // minValue always considered explicitly set, even if null
          'maxValue':
              true, // maxValue always considered explicitly set, even if null
          'defaultValueType': defaultValueType != null,
          'fieldId': fieldId != null,
          'vectorConfig': vectorConfig != null,
        };

  /// check if the property is explicitly set
  bool isExplicitlySet(String propertyName) {
    return _explicitlySet[propertyName] ?? false;
  }

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      'type': type?.name,
      'nullable': nullable,
      'defaultValue': defaultValue,
      'unique': unique,
      'comment': comment,
      'minLength': minLength,
      'maxLength': maxLength,
      'minValue': minValue,
      'maxValue': maxValue,
      if (defaultValueType != null)
        'defaultValueType': defaultValueType.toString().split('.').last,
      'fieldId': fieldId,
      if (vectorConfig != null) 'vectorConfig': vectorConfig!.toJson(),
      '_explicitlySet': _explicitlySet,
    };
  }

  factory FieldSchemaUpdate.fromJson(Map<String, dynamic> json) {
    // Parse default value type
    DefaultValueType? getDefaultValueType() {
      final typeStr = json['defaultValueType'] as String?;
      if (typeStr == null) return null;

      switch (typeStr.toLowerCase()) {
        case 'currenttimestamp':
          return DefaultValueType.currentTimestamp;
        default:
          return DefaultValueType.none;
      }
    }

    final result = FieldSchemaUpdate(
      name: json['name'],
      type: json['type'] != null
          ? DataType.values.firstWhere((e) => e.name == json['type'])
          : null,
      nullable: json['nullable'],
      defaultValue: json['defaultValue'],
      unique: json['unique'],
      comment: json['comment'],
      minLength: json['minLength'],
      maxLength: json['maxLength'],
      minValue: json['minValue'],
      maxValue: json['maxValue'],
      defaultValueType: getDefaultValueType(),
      fieldId: json['fieldId'],
      vectorConfig: json['vectorConfig'] != null
          ? VectorFieldConfig.fromJson(
              json['vectorConfig'] as Map<String, dynamic>)
          : null,
    );

    // if JSON contains _explicitlySet, use it to update _explicitlySet
    if (json['_explicitlySet'] is Map) {
      result._explicitlySet
          .addAll(Map<String, bool>.from(json['_explicitlySet'] as Map));
    }

    return result;
  }
}

/// migration operation
class MigrationOperation {
  final MigrationType type;
  final FieldSchema? field;
  final FieldSchemaUpdate? fieldUpdate;
  final String? fieldName;
  final String? newName;
  final IndexSchema? index;
  final String? indexName;
  final List<String>? fields;
  final bool? unique;
  final String? newTableName;
  final PrimaryKeyConfig? primaryKeyConfig;
  final PrimaryKeyConfig? oldPrimaryKeyConfig;
  final TableTtlConfig? ttlConfig;
  final TableTtlConfig? oldTtlConfig;
  final ForeignKeySchema? foreignKey;
  final String? foreignKeyName;
  final ForeignKeySchema? oldForeignKey;

  const MigrationOperation({
    required this.type,
    this.field,
    this.fieldUpdate,
    this.fieldName,
    this.newName,
    this.index,
    this.indexName,
    this.fields,
    this.unique,
    this.newTableName,
    this.primaryKeyConfig,
    this.oldPrimaryKeyConfig,
    this.ttlConfig,
    this.oldTtlConfig,
    this.foreignKey,
    this.foreignKeyName,
    this.oldForeignKey,
  });

  Map<String, dynamic> toJson() {
    return {
      'type': type.name,
      'field': field?.toJson(),
      'fieldUpdate': fieldUpdate?.toJson(),
      'fieldName': fieldName,
      'newName': newName,
      'index': index?.toJson(),
      'indexName': indexName,
      'fields': fields,
      'unique': unique,
      'newTableName': newTableName,
      'primaryKeyConfig': primaryKeyConfig?.toJson(),
      'oldPrimaryKeyConfig': oldPrimaryKeyConfig?.toJson(),
      'ttlConfig': ttlConfig?.toJson(),
      'oldTtlConfig': oldTtlConfig?.toJson(),
      'foreignKey': foreignKey?.toJson(),
      'foreignKeyName': foreignKeyName,
      'oldForeignKey': oldForeignKey?.toJson(),
    };
  }

  factory MigrationOperation.fromJson(Map<String, dynamic> json) {
    return MigrationOperation(
      type: MigrationType.values.firstWhere(
        (e) => e.name == json['type'],
        orElse: () => MigrationType.addField,
      ),
      field: json['field'] != null ? FieldSchema.fromJson(json['field']) : null,
      fieldUpdate: json['fieldUpdate'] != null
          ? FieldSchemaUpdate.fromJson(json['fieldUpdate'])
          : null,
      fieldName: json['fieldName'],
      newName: json['newName'],
      index: json['index'] != null ? IndexSchema.fromJson(json['index']) : null,
      indexName: json['indexName'],
      fields: (json['fields'] as List?)?.cast<String>(),
      unique: json['unique'],
      newTableName: json['newTableName'],
      primaryKeyConfig: json['primaryKeyConfig'] != null
          ? PrimaryKeyConfig.fromJson(json['primaryKeyConfig'])
          : null,
      oldPrimaryKeyConfig: json['oldPrimaryKeyConfig'] != null
          ? PrimaryKeyConfig.fromJson(json['oldPrimaryKeyConfig'])
          : null,
      ttlConfig: json['ttlConfig'] != null
          ? TableTtlConfig.fromJson(
              Map<String, dynamic>.from(json['ttlConfig'] as Map),
            )
          : null,
      oldTtlConfig: json['oldTtlConfig'] != null
          ? TableTtlConfig.fromJson(
              Map<String, dynamic>.from(json['oldTtlConfig'] as Map),
            )
          : null,
      foreignKey: json['foreignKey'] != null
          ? ForeignKeySchema.fromJson(json['foreignKey'])
          : null,
      foreignKeyName: json['foreignKeyName'],
      oldForeignKey: json['oldForeignKey'] != null
          ? ForeignKeySchema.fromJson(json['oldForeignKey'])
          : null,
    );
  }
}

/// migration task status
class MigrationStatus {
  /// task id
  final String taskId;

  /// whether the task is completed
  final bool isCompleted;

  /// task create time
  final DateTime createTime;

  /// pending spaces
  final List<String> pendingSpaces;

  /// processed spaces count
  final int processedSpacesCount;

  /// total spaces count
  final int totalSpacesCount;

  /// total records processed across all spaces
  final int totalRecordsProcessed;

  /// progress within current space (0.0 - 1.0)
  final double currentSpaceProgress;

  /// current migration throughput (records/second)
  final double throughput;

  /// progress percentage (0-100)
  double get progressPercentage => totalSpacesCount > 0
      ? (processedSpacesCount / totalSpacesCount * 100)
      : 100.0;

  const MigrationStatus({
    required this.taskId,
    required this.isCompleted,
    required this.createTime,
    required this.pendingSpaces,
    required this.processedSpacesCount,
    required this.totalSpacesCount,
    this.totalRecordsProcessed = 0,
    this.currentSpaceProgress = 0.0,
    this.throughput = 0.0,
  });

  Map<String, dynamic> toJson() {
    return {
      'taskId': taskId,
      'isCompleted': isCompleted,
      'createTime': createTime.toIso8601String(),
      'pendingSpaces': pendingSpaces,
      'processedSpacesCount': processedSpacesCount,
      'totalSpacesCount': totalSpacesCount,
      'totalRecordsProcessed': totalRecordsProcessed,
      'currentSpaceProgress': currentSpaceProgress,
      'throughput': throughput,
    };
  }

  factory MigrationStatus.fromJson(Map<String, dynamic> json) {
    return MigrationStatus(
      taskId: json['taskId'],
      isCompleted: json['isCompleted'],
      createTime: DateTime.parse(json['createTime']),
      pendingSpaces: (json['pendingSpaces'] as List).cast<String>(),
      processedSpacesCount: json['processedSpacesCount'],
      totalSpacesCount: json['totalSpacesCount'],
      totalRecordsProcessed: json['totalRecordsProcessed'] ?? 0,
      currentSpaceProgress:
          (json['currentSpaceProgress'] as num?)?.toDouble() ?? 0.0,
      throughput: (json['throughput'] as num?)?.toDouble() ?? 0.0,
    );
  }

  @override
  String toString() {
    return 'MigrationStatus{taskId: $taskId, isCompleted: $isCompleted, '
        'progress: ${progressPercentage.toStringAsFixed(1)}%, '
        'spaceProgress: ${(currentSpaceProgress * 100).toStringAsFixed(1)}%, '
        'records: $totalRecordsProcessed, '
        'throughput: ${throughput.toStringAsFixed(1)} rec/s, '
        'pendingSpaces: ${pendingSpaces.length}}';
  }
}
