import 'dart:typed_data';

import '../../handler/memcomparable.dart';
import '../../model/table_schema.dart';
import '../yield_controller.dart';

/// Per-record prepared unique-index input generated by pure computation.
class PreparedUniqueIndexEntry {
  final dynamic canonicalKey;
  final Uint8List? encodedKeyBytes;

  const PreparedUniqueIndexEntry({
    required this.canonicalKey,
    required this.encodedKeyBytes,
  });
}

/// Pure-compute request for preparing a single unique index across a record batch.
class UniqueIndexPrepareRequest {
  final TableSchema schema;
  final IndexSchema index;
  final List<Map<String, dynamic>> records;
  final List<List<String>?>? changedFieldsByRecord;

  UniqueIndexPrepareRequest({
    required this.schema,
    required this.index,
    required this.records,
    required this.changedFieldsByRecord,
  });
}

/// Prepared entries for a unique index chunk.
class UniqueIndexPrepareResult {
  final List<PreparedUniqueIndexEntry> entries;

  const UniqueIndexPrepareResult({required this.entries});
}

/// Prepare canonical unique keys and encoded memcomparable bytes for a chunk.
Future<UniqueIndexPrepareResult> prepareUniqueIndexChunk(
  UniqueIndexPrepareRequest request,
) async {
  if (request.changedFieldsByRecord != null &&
      request.changedFieldsByRecord!.length != request.records.length) {
    throw ArgumentError(
      'prepareUniqueIndexChunk length mismatch: '
      'records=${request.records.length}, '
      'changedFieldsByRecord=${request.changedFieldsByRecord!.length}',
    );
  }

  final entries = <PreparedUniqueIndexEntry>[];
  final yieldController = YieldController('Compute.uniqueIndex.prepare');

  for (int i = 0; i < request.records.length; i++) {
    await yieldController.maybeYield();

    final changedFields = request.changedFieldsByRecord?[i];
    if (changedFields != null &&
        !request.index.fields.any((field) => changedFields.contains(field))) {
      entries.add(
        const PreparedUniqueIndexEntry(
          canonicalKey: null,
          encodedKeyBytes: null,
        ),
      );
      continue;
    }

    final record = request.records[i];
    final canonicalKey =
        request.schema.createCanonicalIndexKey(request.index.fields, record);
    if (canonicalKey == null) {
      entries.add(
        const PreparedUniqueIndexEntry(
          canonicalKey: null,
          encodedKeyBytes: null,
        ),
      );
      continue;
    }

    Uint8List? encodedKeyBytes;
    final components = <Uint8List>[];
    bool ok = true;
    for (int fieldIndex = 0;
        fieldIndex < request.index.fields.length;
        fieldIndex++) {
      final fieldName = request.index.fields[fieldIndex];
      final dynamic fieldValue;
      if (request.index.fields.length == 1) {
        fieldValue = canonicalKey;
      } else if (canonicalKey is List &&
          canonicalKey.length == request.index.fields.length) {
        fieldValue = canonicalKey[fieldIndex];
      } else {
        ok = false;
        break;
      }

      final component = request.schema.encodeFieldComponentToMemComparable(
        fieldName,
        fieldValue,
        truncateText: false,
      );
      if (component == null) {
        ok = false;
        break;
      }
      components.add(component);
    }
    if (ok && components.isNotEmpty) {
      encodedKeyBytes = MemComparableKey.encodeTuple(components);
    }

    entries.add(
      PreparedUniqueIndexEntry(
        canonicalKey: canonicalKey,
        encodedKeyBytes: encodedKeyBytes,
      ),
    );
  }

  return UniqueIndexPrepareResult(entries: entries);
}
