/// Builds repo-root `llms-full.txt` from `doc/ai/modules/*.md`.
///
/// Usage:
///   dart run doc/ai/scripts/build_llms_full.dart
///   dart run doc/ai/scripts/build_llms_full.dart --check
library;

import 'dart:io';

void main(List<String> args) {
  final check = args.contains('--check');
  final scriptFile = File(Platform.script.toFilePath());
  // doc/ai/scripts -> repo root is ../../..
  final repoRoot = scriptFile.parent.parent.parent.parent;
  final modulesDir = Directory.fromUri(repoRoot.uri.resolve('doc/ai/modules/'));
  final outFile = File.fromUri(repoRoot.uri.resolve('llms-full.txt'));

  if (!modulesDir.existsSync()) {
    stderr.writeln('Modules directory not found: ${modulesDir.path}');
    exitCode = 1;
    return;
  }

  final modules = modulesDir
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.md'))
      .toList()
    ..sort(
        (a, b) => a.uri.pathSegments.last.compareTo(b.uri.pathSegments.last));

  if (modules.isEmpty) {
    stderr.writeln('No modules found in ${modulesDir.path}');
    exitCode = 1;
    return;
  }

  final buf = StringBuffer();
  buf.writeln('# ToStore — Complete AI Programming Specification');
  buf.writeln();
  buf.writeln('> Generated from `doc/ai/modules/*.md`. DO NOT EDIT THIS FILE.');
  buf.writeln('> Regenerate: `dart run doc/ai/scripts/build_llms_full.dart`');
  buf.writeln('> Package: `tostore` · Import: `package:tostore/tostore.dart`');
  buf.writeln();
  buf.writeln(
      'This file is the self-contained corpus for coding agents, @Docs indexing,');
  buf.writeln(
      'single-URL distribution, and LLM training/RAG. Topic modules are the');
  buf.writeln('hand-edited source of truth.');
  buf.writeln();

  for (final file in modules) {
    final name = file.uri.pathSegments.last;
    final body = file.readAsStringSync().replaceAll('\r\n', '\n');
    buf.writeln('<!-- DOC_ID: $name -->');
    buf.writeln();
    buf.writeln(body.trimRight());
    buf.writeln();
    buf.writeln('---');
    buf.writeln();
  }

  buf.writeln('<!-- END OF GENERATED CORPUS -->');
  buf.writeln();

  final next = buf.toString();

  if (check) {
    if (!outFile.existsSync()) {
      stderr.writeln('llms-full.txt missing; run build without --check');
      exitCode = 1;
      return;
    }
    final current = outFile.readAsStringSync().replaceAll('\r\n', '\n');
    if (current != next) {
      stderr.writeln(
          'llms-full.txt is stale. Run: dart run doc/ai/scripts/build_llms_full.dart');
      exitCode = 1;
      return;
    }
    stdout.writeln('llms-full.txt is up to date (${modules.length} modules).');
    return;
  }

  outFile.writeAsStringSync(next);
  stdout.writeln(
      'Wrote ${outFile.path} (${modules.length} modules, ${next.length} bytes).');
}
