import '../handler/value_matcher.dart';
import '../model/db_exception.dart';
import '../model/migration_task.dart';
import '../model/result_status.dart';
import '../model/result_type.dart';
import '../model/table_identity.dart';
import '../model/table_schema.dart';
import '../query/query_condition.dart';

/// Promote-to-PK phase markers persisted on [MigrationTask.promotePhase].
abstract final class PromotePhase {
  static const String creating = 'creating';
  static const String backfilling = 'backfilling';
  static const String swapping = 'swapping';
  static const String done = 'done';
}

/// Hidden shadow table name prefix (not user-facing).
String promoteShadowTableName(String taskId) => '_promote_shadow_$taskId';

bool isPromoteShadowTableName(String tableName) =>
    tableName.startsWith('_promote_shadow_');

/// Runtime descriptor for an in-flight promoteFieldToPrimaryKey migration.
///
/// During migration the logical table stays on [oldSchema] (old PK + sibling
/// field changes). [targetSchema] is the user-facing shape and the shadow
/// table's schema. Online reads hit only the old table; online writes dual-
/// write old-first then upsert/delete the shadow.
class PromoteRuntimeDescriptor {
  final String taskId;
  final TableUid tableUid;
  final TableUid shadowTableUid;
  final TableSchema oldSchema;
  final TableSchema targetSchema;
  final List<MigrationOperation> operations;
  final String sourceFieldName;
  final String? sourceFieldId;
  final IndexUid? sourceUniqueIndexUid;

  const PromoteRuntimeDescriptor({
    required this.taskId,
    required this.tableUid,
    required this.shadowTableUid,
    required this.oldSchema,
    required this.targetSchema,
    required this.operations,
    required this.sourceFieldName,
    this.sourceFieldId,
    this.sourceUniqueIndexUid,
  });

  MigrationOperation? get promoteOp {
    for (final op in operations) {
      if (op.type == MigrationType.promoteFieldToPrimaryKey) return op;
    }
    return null;
  }

  String get targetPkName =>
      promoteOp?.primaryKeyConfig?.name ?? targetSchema.primaryKey;

  String get oldPkName =>
      promoteOp?.oldPrimaryKeyConfig?.name ?? oldSchema.primaryKey;

  /// True when target PK name differs from the source field name.
  bool get needsFieldRename => sourceFieldName != targetPkName;

  /// Map a user-facing (target) field name to the old-table field name.
  String remapFieldNameNewToOld(String field) {
    if (!needsFieldRename) return field;
    if (field == targetPkName) return sourceFieldName;
    if (field.contains('.')) {
      final dot = field.indexOf('.');
      final col = field.substring(dot + 1);
      if (col == targetPkName) {
        return '${field.substring(0, dot)}.$sourceFieldName';
      }
    }
    return field;
  }

  /// Map an old-table field name to the user-facing (target) field name.
  String remapFieldNameOldToNew(String field) {
    if (!needsFieldRename) return field;
    if (field == sourceFieldName) return targetPkName;
    if (field.contains('.')) {
      final dot = field.indexOf('.');
      final col = field.substring(dot + 1);
      if (col == sourceFieldName) {
        return '${field.substring(0, dot)}.$targetPkName';
      }
    }
    return field;
  }
}

/// Result of declarative promote detection.
class PromoteDetection {
  final FieldSchema sourceField;
  final PrimaryKeyConfig targetPk;

  const PromoteDetection({
    required this.sourceField,
    required this.targetPk,
  });
}

/// Whether [type] is an engine-generated primary key (not user-supplied).
bool isAutoGeneratedPrimaryKeyType(PrimaryKeyType type) {
  switch (type) {
    case PrimaryKeyType.sequential:
    case PrimaryKeyType.timestampBased:
    case PrimaryKeyType.datePrefixed:
    case PrimaryKeyType.shortCode:
      return true;
    case PrimaryKeyType.none:
      return false;
  }
}

/// True when [field] is unique via FieldSchema.unique or a unique IndexSchema.
bool isFieldUniqueInSchema(TableSchema schema, FieldSchema field) {
  if (field.unique) return true;
  for (final idx in schema.indexes) {
    if (idx.unique &&
        idx.fields.length == 1 &&
        idx.fields.first == field.name) {
      return true;
    }
  }
  for (final idx in schema.getAllIndexes()) {
    if (idx.unique &&
        idx.fields.length == 1 &&
        idx.fields.first == field.name) {
      return true;
    }
  }
  return false;
}

/// Whether [type] can serve as a primary key value type.
bool isPrimaryKeyCapableDataType(DataType type) {
  switch (type) {
    case DataType.text:
    case DataType.integer:
    case DataType.bigInt:
      return true;
    default:
      return false;
  }
}

/// Detect promote intent from old→new declarative schemas.
///
/// Returns null when the change is not a promote.
PromoteDetection? detectPromoteFieldToPrimaryKey(
  TableSchema oldSchema,
  TableSchema newSchema,
) {
  final oldPk = oldSchema.primaryKeyConfig;
  final newPk = newSchema.primaryKeyConfig;

  if (!isAutoGeneratedPrimaryKeyType(oldPk.type)) return null;
  if (newPk.type != PrimaryKeyType.none) return null;

  // Old PK must be discarded (not demoted into fields).
  if (newSchema.fields.any((f) => f.name == oldPk.name)) return null;

  FieldSchema? candidate;
  for (final oldField in oldSchema.fields) {
    final removed = !newSchema.fields.any((f) => f.name == oldField.name);
    if (!removed) continue;

    final nameMatch = newPk.name == oldField.name;
    final fieldId = oldField.fieldId;
    final idMatch = newPk.fromFieldId != null &&
        fieldId != null &&
        fieldId.isNotEmpty &&
        newPk.fromFieldId == fieldId;
    if (nameMatch || idMatch) {
      candidate = oldField;
      break;
    }
  }
  if (candidate == null) return null;

  // Rename promote requires fromFieldId when names differ.
  if (newPk.name != candidate.name &&
      (newPk.fromFieldId == null || newPk.fromFieldId != candidate.fieldId)) {
    return null;
  }

  return PromoteDetection(
    sourceField: candidate,
    targetPk: newPk.copyWith(clearFromFieldId: true),
  );
}

/// Build a single promote operation from detection.
MigrationOperation buildPromoteOperation({
  required TableSchema oldSchema,
  required PromoteDetection detection,
}) {
  final srcFieldId = detection.sourceField.fieldId;
  return MigrationOperation(
    type: MigrationType.promoteFieldToPrimaryKey,
    fieldName: detection.sourceField.name,
    sourceFieldId:
        (srcFieldId != null && srcFieldId.isNotEmpty) ? srcFieldId : null,
    primaryKeyConfig: detection.targetPk,
    oldPrimaryKeyConfig: oldSchema.primaryKeyConfig,
    discardOldPrimaryKey: true,
  );
}

/// Validate promote constraints. Throws [DbException] on failure.
///
/// When [recordCount] is 0, uniqueness/nullable constraints are not enforced
/// (empty-table fast path).
void validatePromoteFieldToPrimaryKey({
  required TableSchema oldSchema,
  required String sourceFieldName,
  required PrimaryKeyConfig targetPk,
  required int recordCount,
  bool rejectIfReferencedByForeignKey = true,
  List<TableSchema> referencingSchemas = const [],
}) {
  FieldSchema? sourceField;
  for (final f in oldSchema.fields) {
    if (f.name == sourceFieldName) {
      sourceField = f;
      break;
    }
  }
  if (sourceField == null) {
    throw DbException([
      SchemaValidationStatus(
        type: ResultType.devInvalidSchemaFieldName,
        message:
            'Cannot promote field "$sourceFieldName" to primary key in table '
            '"${oldSchema.name}": field does not exist.',
        tableName: oldSchema.name,
        field: sourceFieldName,
      ),
    ]);
  }

  if (!isAutoGeneratedPrimaryKeyType(oldSchema.primaryKeyConfig.type)) {
    throw DbException([
      SchemaValidationStatus(
        type: ResultType.devInvalidSchemaPrimaryKey,
        message:
            'promoteFieldToPrimaryKey requires the current primary key to be '
            'auto-generated; table "${oldSchema.name}" has type '
            '${oldSchema.primaryKeyConfig.type.name}.',
        tableName: oldSchema.name,
        field: oldSchema.primaryKey,
      ),
    ]);
  }

  if (targetPk.type != PrimaryKeyType.none) {
    throw DbException([
      SchemaValidationStatus(
        type: ResultType.devInvalidSchemaPrimaryKey,
        message:
            'promoteFieldToPrimaryKey target primary key type must be none, '
            'got ${targetPk.type.name}.',
        tableName: oldSchema.name,
        field: targetPk.name,
      ),
    ]);
  }

  if (recordCount > 0) {
    if (sourceField.nullable) {
      throw DbException([
        SchemaValidationStatus(
          type: ResultType.devInvalidSchemaPrimaryKey,
          message:
              'Cannot promote nullable field "${sourceField.name}" to primary '
              'key on non-empty table "${oldSchema.name}".',
          tableName: oldSchema.name,
          field: sourceField.name,
        ),
      ]);
    }
    if (!isFieldUniqueInSchema(oldSchema, sourceField)) {
      throw DbException([
        SchemaValidationStatus(
          type: ResultType.devInvalidSchemaPrimaryKey,
          message:
              'Cannot promote non-unique field "${sourceField.name}" to primary '
              'key on non-empty table "${oldSchema.name}". The field must have '
              'unique: true or a unique index.',
          tableName: oldSchema.name,
          field: sourceField.name,
        ),
      ]);
    }
    if (!isPrimaryKeyCapableDataType(sourceField.type)) {
      throw DbException([
        SchemaValidationStatus(
          type: ResultType.devInvalidSchemaPrimaryKey,
          message:
              'Field "${sourceField.name}" type ${sourceField.type.name} cannot '
              'be used as primary key.',
          tableName: oldSchema.name,
          field: sourceField.name,
        ),
      ]);
    }
  }

  if (rejectIfReferencedByForeignKey) {
    final oldPkName = oldSchema.primaryKey;
    for (final child in referencingSchemas) {
      for (final fk in child.foreignKeys) {
        if (fk.referencedTable != oldSchema.name) continue;
        if (fk.referencedFields.contains(oldPkName)) {
          throw DbException([
            SchemaValidationStatus(
              type: ResultType.devInvalidSchemaForeignKey,
              message:
                  'Cannot promote primary key of table "${oldSchema.name}": '
                  'foreign key "${fk.actualName}" on table "${child.name}" '
                  'references the old primary key "$oldPkName". Drop the '
                  'foreign key first.',
              tableName: oldSchema.name,
              field: oldPkName,
              wrongValue: {
                'referencingTable': child.name,
                'foreignKey': fk.actualName,
              },
            ),
          ]);
        }
      }
    }
  }
}

/// Strip promote-only ops and conflicting setPrimaryKeyConfig/removeField
/// that are subsumed by promote, for schema prediction of sibling changes.
List<MigrationOperation> siblingOperationsExcludingPromote(
  List<MigrationOperation> operations,
) {
  MigrationOperation? promote;
  for (final op in operations) {
    if (op.type == MigrationType.promoteFieldToPrimaryKey) {
      promote = op;
      break;
    }
  }
  if (promote == null) return operations;

  final sourceName = promote.fieldName;
  return operations.where((op) {
    if (op.type == MigrationType.promoteFieldToPrimaryKey) return false;
    if (op.type == MigrationType.setPrimaryKeyConfig) return false;
    if (op.type == MigrationType.removeField &&
        sourceName != null &&
        op.fieldName == sourceName) {
      return false;
    }
    // Renaming the promoted source field would desync dual-write / backfill
    // (promoteOp.fieldName stays on the pre-rename name).
    if (op.type == MigrationType.renameField &&
        sourceName != null &&
        op.fieldName == sourceName) {
      return false;
    }
    // Keep source unique index on the old working table for uniqueness.
    if (op.type == MigrationType.removeIndex && sourceName != null) {
      if (op.fields != null &&
          op.fields!.length == 1 &&
          op.fields!.first == sourceName) {
        return false;
      }
      if (op.index != null &&
          op.index!.fields.length == 1 &&
          op.index!.fields.first == sourceName) {
        return false;
      }
    }
    return true;
  }).toList(growable: false);
}

/// Apply only the promote PK reshape in-place (old working → target shape).
///
/// Sibling field changes must already be reflected in [record] (old working
/// schema). Used by online dual-write mirror and promote backfill.
void transformPromoteOldToNewInPlace(
  Map<String, dynamic> record,
  PromoteRuntimeDescriptor desc,
) {
  final promoteOp = desc.promoteOp;
  if (promoteOp == null) return;
  final sourceName = promoteOp.fieldName;
  final targetPk = promoteOp.primaryKeyConfig;
  final oldPk = promoteOp.oldPrimaryKeyConfig;
  if (sourceName == null || targetPk == null) return;

  final sourceValue = record[sourceName];
  if (sourceValue != null) {
    record[targetPk.name] =
        sourceValue is String ? sourceValue : sourceValue.toString();
  }
  if (sourceName != targetPk.name) {
    record.remove(sourceName);
  }
  if (oldPk != null && oldPk.name != targetPk.name) {
    record.remove(oldPk.name);
  }
}

/// Apply only the promote PK reverse reshape in-place (target → old working).
///
/// Does not invent the old auto PK — leave it absent so the old-table insert
/// path generates it. Strips a user-supplied target-PK-as-only-key into the
/// source field slot.
void transformPromoteNewToOldInPlace(
  Map<String, dynamic> record,
  PromoteRuntimeDescriptor desc,
) {
  final promoteOp = desc.promoteOp;
  if (promoteOp == null) return;
  final sourceName = promoteOp.fieldName;
  final targetPk = promoteOp.primaryKeyConfig;
  if (sourceName == null || targetPk == null) return;

  // Target PK value becomes the source unique field on the old table.
  if (sourceName != targetPk.name) {
    if (record.containsKey(targetPk.name) && !record.containsKey(sourceName)) {
      record[sourceName] = record[targetPk.name];
    }
    record.remove(targetPk.name);
  }
}

/// Remap user-facing field names inside a [QueryCondition] tree to old-table
/// names. No-op when source field name equals target PK name.
void remapPromoteConditionNewToOld(
  QueryCondition condition,
  PromoteRuntimeDescriptor desc,
) {
  if (!desc.needsFieldRename) return;
  _remapConditionNodeNewToOld(condition.rootNode, desc);
}

void _remapConditionNodeNewToOld(
  ConditionNode node,
  PromoteRuntimeDescriptor desc,
) {
  if (node.type == NodeType.leaf && node.condition.isNotEmpty) {
    final map = node.condition;
    var changed = false;
    final out = <String, dynamic>{};
    map.forEach((key, value) {
      if (key == 'AND' || key == 'OR') {
        out[key] = value;
        return;
      }
      final remapped = desc.remapFieldNameNewToOld(key);
      if (remapped != key) changed = true;
      out[remapped] = value;
    });
    if (changed) {
      node.condition = out;
    }
    return;
  }
  for (final child in node.children) {
    _remapConditionNodeNewToOld(child, desc);
  }
}

/// Remap orderBy entries (supports `-field` desc prefix and `table.field`).
List<String>? remapPromoteOrderByNewToOld(
  List<String>? orderBy,
  PromoteRuntimeDescriptor desc,
) {
  if (orderBy == null || orderBy.isEmpty || !desc.needsFieldRename) {
    return orderBy;
  }
  var changed = false;
  final out = List<String>.filled(orderBy.length, '', growable: false);
  for (var i = 0; i < orderBy.length; i++) {
    final raw = orderBy[i];
    final descPrefix = raw.startsWith('-');
    final name = descPrefix ? raw.substring(1) : raw;
    final remapped = desc.remapFieldNameNewToOld(name);
    if (remapped != name) changed = true;
    out[i] = descPrefix ? '-$remapped' : remapped;
  }
  return changed ? out : orderBy;
}

/// Remap select/groupBy field name lists.
List<String>? remapPromoteFieldListNewToOld(
  List<String>? fields,
  PromoteRuntimeDescriptor desc,
) {
  if (fields == null || fields.isEmpty || !desc.needsFieldRename) {
    return fields;
  }
  var changed = false;
  final out = List<String>.filled(fields.length, '', growable: false);
  for (var i = 0; i < fields.length; i++) {
    final remapped = desc.remapFieldNameNewToOld(fields[i]);
    if (remapped != fields[i]) changed = true;
    out[i] = remapped;
  }
  return changed ? out : fields;
}

/// Convert an old-table success key (auto PK) lookup is not needed when the
/// caller already has the old record - extract the user-facing PK string.
String? promoteUserFacingPkFromOldRecord(
  Map<String, dynamic> oldRecord,
  PromoteRuntimeDescriptor desc,
) {
  final v = oldRecord[desc.sourceFieldName] ?? oldRecord[desc.targetPkName];
  return v?.toString();
}

/// Find the unique index uid covering [sourceFieldName] on [oldSchema], if any.
IndexUid? findSourceUniqueIndexUid(
  TableSchema oldSchema,
  String sourceFieldName,
) {
  for (final idx in oldSchema.getAllIndexes()) {
    if (idx.unique &&
        idx.fields.length == 1 &&
        idx.fields.first == sourceFieldName &&
        idx.indexUid.value.isNotEmpty) {
      return idx.indexUid;
    }
  }
  return null;
}
