import 'dart:convert';
import 'dart:typed_data';

import '../model/data_store_config.dart';
import '../model/meta_info.dart';
import '../model/migration_task.dart';
import '../model/migration_write_mode.dart';
import '../model/result_status.dart';
import '../model/table_identity.dart';
import '../model/table_schema.dart';
import '../model/wal_pointer.dart';
import 'binary_codec.dart';
import 'binary_map_codec.dart';
import 'meta_file_codec.dart';
import 'schema_binary_codec.dart';
import 'wal_meta_codec.dart';

/// Stable field IDs for [MigrationTask]. Never reuse IDs.
abstract final class MigrationTaskFieldId {
  static const int taskId = 1;
  static const int tableUid = 2;
  static const int isSchemaUpdated = 3;
  static const int pendingMigrationSpaces = 4;
  static const int operations = 5;
  static const int createTimeUs = 6;
  static const int dirIndex = 7;
  static const int isAutoGenerated = 8;
  static const int oldSchemaSnapshot = 9;
  static const int targetSchemaSnapshot = 10;
  static const int oldFieldLayoutSnapshot = 11;
  static const int schemaCutoverWalPointer = 12;
  static const int forceDataMigration = 13;
  static const int spaceCheckpointKeys = 14;
  static const int backupPath = 15;
  static const int writeMode = 16;
  static const int specificIndexUids = 17;
  static const int errors = 18;
  static const int estimateDurationUs = 19;
  static const int referencingChildIndexesToDrop = 20;
  static const int targetFieldLayoutSnapshot = 21;
  // Reserved 40–63.
}

abstract final class SpaceCheckpointFieldId {
  static const int spaceName = 1;
  static const int keyBytes = 2;
}

abstract final class ChildIndexesDropFieldId {
  static const int childTableUid = 1;
  static const int indexUids = 2;
}

abstract final class MigrationOperationFieldId {
  static const int type = 1;
  static const int field = 2;
  static const int fieldUpdate = 3;
  static const int fieldName = 4;
  static const int newName = 5;
  static const int index = 6;
  static const int indexName = 7;
  static const int fields = 8;
  static const int unique = 9;
  static const int newTableName = 10;
  static const int primaryKeyConfig = 11;
  static const int oldPrimaryKeyConfig = 12;
  static const int ttlConfig = 13;
  static const int oldTtlConfig = 14;
  static const int foreignKey = 15;
  static const int foreignKeyName = 16;
  static const int oldForeignKey = 17;
  // Reserved 30–39.
}

abstract final class FieldSchemaUpdateFieldId {
  static const int name = 1;
  static const int type = 2;
  static const int nullable = 3;
  static const int defaultValue = 4;
  static const int unique = 5;
  static const int comment = 6;
  static const int minLength = 7;
  static const int maxLength = 8;
  static const int minValue = 9;
  static const int maxValue = 10;
  static const int defaultValueType = 11;
  static const int fieldId = 12;
  static const int vectorConfig = 13;
  static const int explicitlySet = 14;
}

abstract final class ExplicitSetEntryFieldId {
  static const int key = 1;
  static const int value = 2;
}

/// Field-tag + TOBF codec for [MigrationTask].
final class MigrationTaskCodec {
  MigrationTaskCodec._();

  static T _enumAt<T extends Enum>(List<T> values, int index, T fallback) {
    if (index < 0 || index >= values.length) return fallback;
    return values[index];
  }

  static Uint8List encodePayload(MigrationTask task) {
    final w = BinaryWriter(initialCapacity: 1024);

    w.writeFieldTag(MigrationTaskFieldId.taskId, WireType.lengthDelimited);
    w.writeString(task.taskId);
    w.writeFieldTag(MigrationTaskFieldId.tableUid, WireType.lengthDelimited);
    w.writeString(task.tableUid.value);

    w.writeFieldTag(MigrationTaskFieldId.isSchemaUpdated, WireType.varint);
    w.writeBool(task.isSchemaUpdated);

    for (final space in task.pendingMigrationSpaces) {
      w.writeFieldTag(MigrationTaskFieldId.pendingMigrationSpaces,
          WireType.lengthDelimited);
      w.writeString(space);
    }
    for (final op in task.operations) {
      w.writeMessage(MigrationTaskFieldId.operations, (sw) {
        _writeOperation(sw, op);
      });
    }

    w.writeFieldTag(MigrationTaskFieldId.createTimeUs, WireType.fixed64);
    w.writeFixed64(task.createTime.toUtc().microsecondsSinceEpoch);

    w.writeFieldTag(MigrationTaskFieldId.dirIndex, WireType.varint);
    w.writeVarint(task.dirIndex);

    if (!task.isAutoGenerated) {
      w.writeFieldTag(MigrationTaskFieldId.isAutoGenerated, WireType.varint);
      w.writeBool(false);
    }

    if (task.oldSchemaSnapshot != null) {
      w.writeMessage(MigrationTaskFieldId.oldSchemaSnapshot, (sw) {
        SchemaBinaryCodec.writeTableSchema(sw, task.oldSchemaSnapshot!);
      });
    }
    if (task.targetSchemaSnapshot != null) {
      w.writeMessage(MigrationTaskFieldId.targetSchemaSnapshot, (sw) {
        SchemaBinaryCodec.writeTableSchema(sw, task.targetSchemaSnapshot!);
      });
    }
    if (task.oldFieldLayoutSnapshot != null) {
      w.writeMessage(MigrationTaskFieldId.oldFieldLayoutSnapshot, (sw) {
        SchemaBinaryCodec.writeFieldStorageLayout(
            sw, task.oldFieldLayoutSnapshot!);
      });
    }
    if (task.targetFieldLayoutSnapshot != null) {
      w.writeMessage(MigrationTaskFieldId.targetFieldLayoutSnapshot, (sw) {
        SchemaBinaryCodec.writeFieldStorageLayout(
            sw, task.targetFieldLayoutSnapshot!);
      });
    }
    if (task.schemaCutoverWalPointer != null) {
      w.writeMessage(MigrationTaskFieldId.schemaCutoverWalPointer, (sw) {
        _writeWalPointer(sw, task.schemaCutoverWalPointer!);
      });
    }
    if (task.forceDataMigration) {
      w.writeFieldTag(MigrationTaskFieldId.forceDataMigration, WireType.varint);
      w.writeBool(true);
    }

    task.spaceCheckpointKeys.forEach((space, b64) {
      w.writeMessage(MigrationTaskFieldId.spaceCheckpointKeys, (sw) {
        sw.writeFieldTag(
            SpaceCheckpointFieldId.spaceName, WireType.lengthDelimited);
        sw.writeString(space);
        sw.writeFieldTag(
            SpaceCheckpointFieldId.keyBytes, WireType.lengthDelimited);
        sw.writeBytes(base64Decode(b64));
      });
    });

    if (task.backupPath != null) {
      w.writeFieldTag(
          MigrationTaskFieldId.backupPath, WireType.lengthDelimited);
      w.writeString(task.backupPath!);
    }
    if (task.writeMode != null) {
      w.writeFieldTag(MigrationTaskFieldId.writeMode, WireType.varint);
      w.writeVarint(task.writeMode!.index);
    }
    if (task.specificIndexUids != null) {
      for (final uid in task.specificIndexUids!) {
        w.writeFieldTag(
            MigrationTaskFieldId.specificIndexUids, WireType.lengthDelimited);
        w.writeString(uid.value);
      }
    }
    if (task.errors != null) {
      for (final err in task.errors!) {
        w.writeFieldTag(MigrationTaskFieldId.errors, WireType.lengthDelimited);
        w.writeBytes(BinaryMapCodec.encodeMap(err.toJson()));
      }
    }
    if (task.estimateDuration != null) {
      w.writeFieldTag(MigrationTaskFieldId.estimateDurationUs, WireType.varint);
      w.writeVarint(task.estimateDuration!.inMicroseconds);
    }
    if (task.referencingChildIndexesToDrop != null) {
      task.referencingChildIndexesToDrop!.forEach((childUid, indexUids) {
        w.writeMessage(MigrationTaskFieldId.referencingChildIndexesToDrop,
            (sw) {
          sw.writeFieldTag(
              ChildIndexesDropFieldId.childTableUid, WireType.lengthDelimited);
          sw.writeString(childUid.value);
          for (final iu in indexUids) {
            sw.writeFieldTag(
                ChildIndexesDropFieldId.indexUids, WireType.lengthDelimited);
            sw.writeString(iu.value);
          }
        });
      });
    }

    return w.view;
  }

  static MigrationTask decodePayload(Uint8List bytes) {
    final r = BinaryReader(bytes);
    var taskId = '';
    var tableUid = TableUid.empty;
    var isSchemaUpdated = false;
    final pendingSpaces = <String>[];
    final operations = <MigrationOperation>[];
    var createTimeUs = 0;
    var dirIndex = 0;
    var isAutoGenerated = true;
    TableSchema? oldSchema;
    TableSchema? targetSchema;
    FieldStorageLayout? oldFieldLayout;
    FieldStorageLayout? targetFieldLayout;
    WalPointer? cutover;
    var forceDataMigration = false;
    final spaceCheckpointKeys = <String, String>{};
    String? backupPath;
    MigrationWriteMode? writeMode;
    List<IndexUid>? specificIndexUids;
    var sawSpecific = false;
    List<ResultStatus>? errors;
    var sawErrors = false;
    Duration? estimateDuration;
    Map<TableUid, List<IndexUid>>? childDrops;
    var sawChildDrops = false;

    while (!r.isEOF) {
      final (fieldId, wireType) = r.readFieldTag();
      switch (fieldId) {
        case MigrationTaskFieldId.taskId:
          taskId = r.readString();
          break;
        case MigrationTaskFieldId.tableUid:
          tableUid = TableUid(r.readString());
          break;
        case MigrationTaskFieldId.isSchemaUpdated:
          isSchemaUpdated = r.readBool();
          break;
        case MigrationTaskFieldId.pendingMigrationSpaces:
          pendingSpaces.add(r.readString());
          break;
        case MigrationTaskFieldId.operations:
          r.readMessage((nr, _) {
            operations.add(_readOperation(nr));
          });
          break;
        case MigrationTaskFieldId.createTimeUs:
          createTimeUs = r.readFixed64();
          break;
        case MigrationTaskFieldId.dirIndex:
          dirIndex = r.readVarint();
          break;
        case MigrationTaskFieldId.isAutoGenerated:
          isAutoGenerated = r.readBool();
          break;
        case MigrationTaskFieldId.oldSchemaSnapshot:
          r.readMessage((nr, _) {
            oldSchema = SchemaBinaryCodec.readTableSchema(nr);
          });
          break;
        case MigrationTaskFieldId.targetSchemaSnapshot:
          r.readMessage((nr, _) {
            targetSchema = SchemaBinaryCodec.readTableSchema(nr);
          });
          break;
        case MigrationTaskFieldId.oldFieldLayoutSnapshot:
          r.readMessage((nr, _) {
            oldFieldLayout = SchemaBinaryCodec.readFieldStorageLayout(nr);
          });
          break;
        case MigrationTaskFieldId.targetFieldLayoutSnapshot:
          r.readMessage((nr, _) {
            targetFieldLayout = SchemaBinaryCodec.readFieldStorageLayout(nr);
          });
          break;
        case MigrationTaskFieldId.schemaCutoverWalPointer:
          r.readMessage((nr, _) {
            cutover = _readWalPointer(nr);
          });
          break;
        case MigrationTaskFieldId.forceDataMigration:
          forceDataMigration = r.readBool();
          break;
        case MigrationTaskFieldId.spaceCheckpointKeys:
          r.readMessage((nr, _) {
            String? space;
            Uint8List? keyBytes;
            while (!nr.isEOF) {
              final (fid, wt) = nr.readFieldTag();
              switch (fid) {
                case SpaceCheckpointFieldId.spaceName:
                  space = nr.readString();
                  break;
                case SpaceCheckpointFieldId.keyBytes:
                  keyBytes = nr.readBytes();
                  break;
                default:
                  nr.skipField(wt);
                  break;
              }
            }
            if (space != null && keyBytes != null) {
              spaceCheckpointKeys[space] = base64Encode(keyBytes);
            }
          });
          break;
        case MigrationTaskFieldId.backupPath:
          backupPath = r.readString();
          break;
        case MigrationTaskFieldId.writeMode:
          writeMode = _enumAt(
            MigrationWriteMode.values,
            r.readVarint(),
            MigrationWriteMode.none,
          );
          break;
        case MigrationTaskFieldId.specificIndexUids:
          sawSpecific = true;
          specificIndexUids ??= <IndexUid>[];
          specificIndexUids.add(IndexUid(r.readString()));
          break;
        case MigrationTaskFieldId.errors:
          sawErrors = true;
          errors ??= <ResultStatus>[];
          final map = BinaryMapCodec.decodeMap(r.readBytes());
          if (map != null) {
            errors.add(ResultStatus.fromJson(map));
          }
          break;
        case MigrationTaskFieldId.estimateDurationUs:
          estimateDuration = Duration(microseconds: r.readVarint());
          break;
        case MigrationTaskFieldId.referencingChildIndexesToDrop:
          sawChildDrops = true;
          final drops = childDrops ??= <TableUid, List<IndexUid>>{};
          r.readMessage((nr, _) {
            var childUid = TableUid.empty;
            final indexUids = <IndexUid>[];
            while (!nr.isEOF) {
              final (fid, wt) = nr.readFieldTag();
              switch (fid) {
                case ChildIndexesDropFieldId.childTableUid:
                  childUid = TableUid(nr.readString());
                  break;
                case ChildIndexesDropFieldId.indexUids:
                  indexUids.add(IndexUid(nr.readString()));
                  break;
                default:
                  nr.skipField(wt);
                  break;
              }
            }
            if (childUid.isNotEmpty) {
              drops[childUid] = indexUids;
            }
          });
          break;
        default:
          r.skipField(wireType);
          break;
      }
    }

    return MigrationTask(
      taskId: taskId,
      tableUid: tableUid,
      isSchemaUpdated: isSchemaUpdated,
      pendingMigrationSpaces: pendingSpaces,
      operations: operations,
      createTime:
          DateTime.fromMicrosecondsSinceEpoch(createTimeUs, isUtc: true),
      dirIndex: dirIndex,
      isAutoGenerated: isAutoGenerated,
      oldSchemaSnapshot: oldSchema,
      targetSchemaSnapshot: targetSchema,
      oldFieldLayoutSnapshot: oldFieldLayout,
      targetFieldLayoutSnapshot: targetFieldLayout,
      schemaCutoverWalPointer: cutover,
      forceDataMigration: forceDataMigration,
      spaceCheckpointKeys: spaceCheckpointKeys,
      backupPath: backupPath,
      writeMode: writeMode,
      specificIndexUids: sawSpecific ? (specificIndexUids ?? const []) : null,
      errors: sawErrors ? (errors ?? const []) : null,
      estimateDuration: estimateDuration,
      referencingChildIndexesToDrop:
          sawChildDrops ? (childDrops ?? const {}) : null,
    );
  }

  static Uint8List encodeFile(
    MigrationTask task, {
    required EncryptionConfig? encryptionConfig,
  }) {
    return MetaFileCodec.encodeFile(
      encodePayload(task),
      encrypt: MetaFileCodec.shouldEncrypt(encryptionConfig),
      aad: MetaFileCodec.migrationTaskAad,
    );
  }

  static MigrationTask decodeFile(Uint8List frameBytes) {
    return decodePayload(
      MetaFileCodec.decodeFile(
        frameBytes,
        aad: MetaFileCodec.migrationTaskAad,
        maxBodyLimit: MetaFileCodec.maxBodyBytes,
      ),
    );
  }

  static void _writeWalPointer(BinaryWriter w, WalPointer p) {
    w.writeFieldTag(WalPointerFieldId.partitionIndex, WireType.varint);
    w.writeZigZag64(p.partitionIndex);
    w.writeFieldTag(WalPointerFieldId.entrySeq, WireType.varint);
    w.writeZigZag64(p.entrySeq);
  }

  static WalPointer _readWalPointer(BinaryReader r) {
    var partitionIndex = 0;
    var entrySeq = 0;
    while (!r.isEOF) {
      final (fieldId, wireType) = r.readFieldTag();
      switch (fieldId) {
        case WalPointerFieldId.partitionIndex:
          partitionIndex = r.readZigZag64();
          break;
        case WalPointerFieldId.entrySeq:
          entrySeq = r.readZigZag64();
          break;
        default:
          r.skipField(wireType);
          break;
      }
    }
    return WalPointer(partitionIndex: partitionIndex, entrySeq: entrySeq);
  }

  static void _writeOperation(BinaryWriter w, MigrationOperation op) {
    w.writeFieldTag(MigrationOperationFieldId.type, WireType.varint);
    w.writeVarint(op.type.index);

    if (op.field != null) {
      w.writeMessage(MigrationOperationFieldId.field, (sw) {
        SchemaBinaryCodec.writeFieldSchema(sw, op.field!);
      });
    }
    if (op.fieldUpdate != null) {
      w.writeMessage(MigrationOperationFieldId.fieldUpdate, (sw) {
        _writeFieldUpdate(sw, op.fieldUpdate!);
      });
    }
    if (op.fieldName != null) {
      w.writeFieldTag(
          MigrationOperationFieldId.fieldName, WireType.lengthDelimited);
      w.writeString(op.fieldName!);
    }
    if (op.newName != null) {
      w.writeFieldTag(
          MigrationOperationFieldId.newName, WireType.lengthDelimited);
      w.writeString(op.newName!);
    }
    if (op.index != null) {
      w.writeMessage(MigrationOperationFieldId.index, (sw) {
        SchemaBinaryCodec.writeIndexSchema(sw, op.index!);
      });
    }
    if (op.indexName != null) {
      w.writeFieldTag(
          MigrationOperationFieldId.indexName, WireType.lengthDelimited);
      w.writeString(op.indexName!);
    }
    if (op.fields != null) {
      for (final f in op.fields!) {
        w.writeFieldTag(
            MigrationOperationFieldId.fields, WireType.lengthDelimited);
        w.writeString(f);
      }
    }
    if (op.unique != null) {
      w.writeFieldTag(MigrationOperationFieldId.unique, WireType.varint);
      w.writeBool(op.unique!);
    }
    if (op.newTableName != null) {
      w.writeFieldTag(
          MigrationOperationFieldId.newTableName, WireType.lengthDelimited);
      w.writeString(op.newTableName!);
    }
    if (op.primaryKeyConfig != null) {
      w.writeMessage(MigrationOperationFieldId.primaryKeyConfig, (sw) {
        SchemaBinaryCodec.writePrimaryKeyConfig(sw, op.primaryKeyConfig!);
      });
    }
    if (op.oldPrimaryKeyConfig != null) {
      w.writeMessage(MigrationOperationFieldId.oldPrimaryKeyConfig, (sw) {
        SchemaBinaryCodec.writePrimaryKeyConfig(sw, op.oldPrimaryKeyConfig!);
      });
    }
    if (op.ttlConfig != null) {
      w.writeMessage(MigrationOperationFieldId.ttlConfig, (sw) {
        SchemaBinaryCodec.writeTableTtlConfig(sw, op.ttlConfig!);
      });
    }
    if (op.oldTtlConfig != null) {
      w.writeMessage(MigrationOperationFieldId.oldTtlConfig, (sw) {
        SchemaBinaryCodec.writeTableTtlConfig(sw, op.oldTtlConfig!);
      });
    }
    if (op.foreignKey != null) {
      w.writeMessage(MigrationOperationFieldId.foreignKey, (sw) {
        SchemaBinaryCodec.writeForeignKeySchema(sw, op.foreignKey!);
      });
    }
    if (op.foreignKeyName != null) {
      w.writeFieldTag(
          MigrationOperationFieldId.foreignKeyName, WireType.lengthDelimited);
      w.writeString(op.foreignKeyName!);
    }
    if (op.oldForeignKey != null) {
      w.writeMessage(MigrationOperationFieldId.oldForeignKey, (sw) {
        SchemaBinaryCodec.writeForeignKeySchema(sw, op.oldForeignKey!);
      });
    }
  }

  static MigrationOperation _readOperation(BinaryReader r) {
    var type = MigrationType.addField;
    FieldSchema? field;
    FieldSchemaUpdate? fieldUpdate;
    String? fieldName;
    String? newName;
    IndexSchema? index;
    String? indexName;
    List<String>? fields;
    var sawFields = false;
    bool? unique;
    String? newTableName;
    PrimaryKeyConfig? primaryKeyConfig;
    PrimaryKeyConfig? oldPrimaryKeyConfig;
    TableTtlConfig? ttlConfig;
    TableTtlConfig? oldTtlConfig;
    ForeignKeySchema? foreignKey;
    String? foreignKeyName;
    ForeignKeySchema? oldForeignKey;

    while (!r.isEOF) {
      final (fid, wireType) = r.readFieldTag();
      switch (fid) {
        case MigrationOperationFieldId.type:
          type = _enumAt(
            MigrationType.values,
            r.readVarint(),
            MigrationType.addField,
          );
          break;
        case MigrationOperationFieldId.field:
          r.readMessage((nr, _) {
            field = SchemaBinaryCodec.readFieldSchema(nr);
          });
          break;
        case MigrationOperationFieldId.fieldUpdate:
          r.readMessage((nr, _) {
            fieldUpdate = _readFieldUpdate(nr);
          });
          break;
        case MigrationOperationFieldId.fieldName:
          fieldName = r.readString();
          break;
        case MigrationOperationFieldId.newName:
          newName = r.readString();
          break;
        case MigrationOperationFieldId.index:
          r.readMessage((nr, _) {
            index = SchemaBinaryCodec.readIndexSchema(nr);
          });
          break;
        case MigrationOperationFieldId.indexName:
          indexName = r.readString();
          break;
        case MigrationOperationFieldId.fields:
          sawFields = true;
          fields ??= <String>[];
          fields.add(r.readString());
          break;
        case MigrationOperationFieldId.unique:
          unique = r.readBool();
          break;
        case MigrationOperationFieldId.newTableName:
          newTableName = r.readString();
          break;
        case MigrationOperationFieldId.primaryKeyConfig:
          r.readMessage((nr, _) {
            primaryKeyConfig = SchemaBinaryCodec.readPrimaryKeyConfig(nr);
          });
          break;
        case MigrationOperationFieldId.oldPrimaryKeyConfig:
          r.readMessage((nr, _) {
            oldPrimaryKeyConfig = SchemaBinaryCodec.readPrimaryKeyConfig(nr);
          });
          break;
        case MigrationOperationFieldId.ttlConfig:
          r.readMessage((nr, _) {
            ttlConfig = SchemaBinaryCodec.readTableTtlConfig(nr);
          });
          break;
        case MigrationOperationFieldId.oldTtlConfig:
          r.readMessage((nr, _) {
            oldTtlConfig = SchemaBinaryCodec.readTableTtlConfig(nr);
          });
          break;
        case MigrationOperationFieldId.foreignKey:
          r.readMessage((nr, _) {
            foreignKey = SchemaBinaryCodec.readForeignKeySchema(nr);
          });
          break;
        case MigrationOperationFieldId.foreignKeyName:
          foreignKeyName = r.readString();
          break;
        case MigrationOperationFieldId.oldForeignKey:
          r.readMessage((nr, _) {
            oldForeignKey = SchemaBinaryCodec.readForeignKeySchema(nr);
          });
          break;
        default:
          r.skipField(wireType);
          break;
      }
    }

    return MigrationOperation(
      type: type,
      field: field,
      fieldUpdate: fieldUpdate,
      fieldName: fieldName,
      newName: newName,
      index: index,
      indexName: indexName,
      fields: sawFields ? (fields ?? const []) : null,
      unique: unique,
      newTableName: newTableName,
      primaryKeyConfig: primaryKeyConfig,
      oldPrimaryKeyConfig: oldPrimaryKeyConfig,
      ttlConfig: ttlConfig,
      oldTtlConfig: oldTtlConfig,
      foreignKey: foreignKey,
      foreignKeyName: foreignKeyName,
      oldForeignKey: oldForeignKey,
    );
  }

  static void _writeFieldUpdate(BinaryWriter w, FieldSchemaUpdate update) {
    w.writeFieldTag(FieldSchemaUpdateFieldId.name, WireType.lengthDelimited);
    w.writeString(update.name);
    if (update.type != null) {
      w.writeFieldTag(FieldSchemaUpdateFieldId.type, WireType.varint);
      w.writeVarint(update.type!.index);
    }
    if (update.nullable != null) {
      w.writeFieldTag(FieldSchemaUpdateFieldId.nullable, WireType.varint);
      w.writeBool(update.nullable!);
    }
    if (update.isExplicitlySet('defaultValue')) {
      SchemaBinaryCodec.writeDynamicValue(
        w,
        FieldSchemaUpdateFieldId.defaultValue,
        update.defaultValue,
      );
    }
    if (update.unique != null) {
      w.writeFieldTag(FieldSchemaUpdateFieldId.unique, WireType.varint);
      w.writeBool(update.unique!);
    }
    if (update.isExplicitlySet('comment')) {
      w.writeFieldTag(
          FieldSchemaUpdateFieldId.comment, WireType.lengthDelimited);
      w.writeString(update.comment ?? '');
    }
    if (update.isExplicitlySet('minLength') && update.minLength != null) {
      w.writeFieldTag(FieldSchemaUpdateFieldId.minLength, WireType.varint);
      w.writeZigZag64(update.minLength!);
    }
    if (update.isExplicitlySet('maxLength') && update.maxLength != null) {
      w.writeFieldTag(FieldSchemaUpdateFieldId.maxLength, WireType.varint);
      w.writeZigZag64(update.maxLength!);
    }
    if (update.isExplicitlySet('minValue')) {
      SchemaBinaryCodec.writeDynamicValue(
        w,
        FieldSchemaUpdateFieldId.minValue,
        update.minValue,
      );
    }
    if (update.isExplicitlySet('maxValue')) {
      SchemaBinaryCodec.writeDynamicValue(
        w,
        FieldSchemaUpdateFieldId.maxValue,
        update.maxValue,
      );
    }
    if (update.defaultValueType != null) {
      w.writeFieldTag(
          FieldSchemaUpdateFieldId.defaultValueType, WireType.varint);
      w.writeVarint(update.defaultValueType!.index);
    }
    if (update.fieldId != null) {
      w.writeFieldTag(
          FieldSchemaUpdateFieldId.fieldId, WireType.lengthDelimited);
      w.writeString(update.fieldId!);
    }
    if (update.vectorConfig != null) {
      w.writeMessage(FieldSchemaUpdateFieldId.vectorConfig, (sw) {
        SchemaBinaryCodec.writeVectorFieldConfig(sw, update.vectorConfig!);
      });
    }
    update.explicitlySetFlags.forEach((key, value) {
      w.writeMessage(FieldSchemaUpdateFieldId.explicitlySet, (sw) {
        sw.writeFieldTag(ExplicitSetEntryFieldId.key, WireType.lengthDelimited);
        sw.writeString(key);
        sw.writeFieldTag(ExplicitSetEntryFieldId.value, WireType.varint);
        sw.writeBool(value);
      });
    });
  }

  static FieldSchemaUpdate _readFieldUpdate(BinaryReader r) {
    var name = '';
    DataType? type;
    bool? nullable;
    dynamic defaultValue;
    bool? unique;
    String? comment;
    int? minLength;
    int? maxLength;
    num? minValue;
    num? maxValue;
    DefaultValueType? defaultValueType;
    String? fieldId;
    VectorFieldConfig? vectorConfig;
    final explicitlySet = <String, bool>{};
    var sawMinLength = false;
    var sawMaxLength = false;

    while (!r.isEOF) {
      final (fid, wireType) = r.readFieldTag();
      switch (fid) {
        case FieldSchemaUpdateFieldId.name:
          name = r.readString();
          break;
        case FieldSchemaUpdateFieldId.type:
          type = _enumAt(DataType.values, r.readVarint(), DataType.text);
          break;
        case FieldSchemaUpdateFieldId.nullable:
          nullable = r.readBool();
          break;
        case FieldSchemaUpdateFieldId.defaultValue:
          defaultValue = SchemaBinaryCodec.readDynamicValue(r);
          break;
        case FieldSchemaUpdateFieldId.unique:
          unique = r.readBool();
          break;
        case FieldSchemaUpdateFieldId.comment:
          comment = r.readString();
          break;
        case FieldSchemaUpdateFieldId.minLength:
          sawMinLength = true;
          minLength = r.readZigZag64();
          break;
        case FieldSchemaUpdateFieldId.maxLength:
          sawMaxLength = true;
          maxLength = r.readZigZag64();
          break;
        case FieldSchemaUpdateFieldId.minValue:
          final v = SchemaBinaryCodec.readDynamicValue(r);
          minValue = v is num ? v : null;
          break;
        case FieldSchemaUpdateFieldId.maxValue:
          final v = SchemaBinaryCodec.readDynamicValue(r);
          maxValue = v is num ? v : null;
          break;
        case FieldSchemaUpdateFieldId.defaultValueType:
          defaultValueType = _enumAt(
            DefaultValueType.values,
            r.readVarint(),
            DefaultValueType.none,
          );
          break;
        case FieldSchemaUpdateFieldId.fieldId:
          fieldId = r.readString();
          break;
        case FieldSchemaUpdateFieldId.vectorConfig:
          r.readMessage((nr, _) {
            vectorConfig = SchemaBinaryCodec.readVectorFieldConfig(nr);
          });
          break;
        case FieldSchemaUpdateFieldId.explicitlySet:
          r.readMessage((nr, _) {
            String? key;
            var value = false;
            while (!nr.isEOF) {
              final (efid, ewt) = nr.readFieldTag();
              switch (efid) {
                case ExplicitSetEntryFieldId.key:
                  key = nr.readString();
                  break;
                case ExplicitSetEntryFieldId.value:
                  value = nr.readBool();
                  break;
                default:
                  nr.skipField(ewt);
                  break;
              }
            }
            if (key != null) explicitlySet[key] = value;
          });
          break;
        default:
          r.skipField(wireType);
          break;
      }
    }

    // When length fields are explicitly set to null, the int field is omitted.
    if (!sawMinLength && explicitlySet['minLength'] == true) {
      minLength = null;
    }
    if (!sawMaxLength && explicitlySet['maxLength'] == true) {
      maxLength = null;
    }

    return FieldSchemaUpdate.rehydrate(
      name: name,
      type: type,
      nullable: nullable,
      defaultValue: defaultValue,
      unique: unique,
      comment: comment,
      minLength: minLength,
      maxLength: maxLength,
      minValue: minValue,
      maxValue: maxValue,
      defaultValueType: defaultValueType,
      fieldId: fieldId,
      vectorConfig: vectorConfig,
      explicitlySet: explicitlySet.isEmpty ? null : explicitlySet,
    );
  }
}
